Update QSG according with OB3
wso2/demo-open-banking.github.io pull request #48
Opened 2022-10-29 19:33 UTC by isharailanga

This PR is to update the Sandbox Guide according to https://docs.google.com/document/d/1Xfg2QeotfNvdcKFDAa5kjexRQWGI2jGiKmnh7EeOPsg/edit.  

This will fix https://github.com/wso2/docs-open-banking/issues/654

2022-11-01 08:00 UTC, ChinthakaJ98 requested changes

2022-11-01 08:00 UTC, ChinthakaJ98 commented on sandbox-guide.md
> +   - CDR Dynamic Client Registration API: To create Dynamic Client Registration (DCR) Applications
We will remove the usage of the term "CDR" as the API names have been changed now. Please check for the other usages as well.

2022-11-01 08:00 UTC, ChinthakaJ98 commented on sandbox-guide.md
> +- If you already have a Client ID of a registered application in the portal, skip the steps above.
Can we shift this to the top of the content on registering an application so that the user will know about it before start creating an application?

2022-11-01 08:00 UTC, ChinthakaJ98 commented on sandbox-guide.md
> +- From the response, copy the **Client ID** of the application.
We need to mention that the user needs to save that Client ID then and there as if the page is refreshed they will need to create another application. Also that the same Client ID can be used next time when they are trying out the flow again.

2022-11-01 08:00 UTC, ChinthakaJ98 commented on sandbox-guide.md
> +- In the **Security** section, enter the access token obtained in the previous step.
It would be better to mention as the application access token

2022-11-01 08:00 UTC, ChinthakaJ98 commented on sandbox-guide.md
> +- In the **Security** section, enter the access token obtained in the previous step.
It would be better to mention as the user access token

2022-11-01 08:00 UTC, ChinthakaJ98 commented on sandbox-guide.md
> +## Sign up as an API consumer
Will it be better to say Third-party Provider(TPP)?

2022-11-01 08:29 UTC, isharailanga commented on sandbox-guide.md
> +## Sign up as an API consumer
TPP is a term used in the PSD2.  Different specs use different terms so for OB3 we agreed on a common term "API Consumer  Application" to represent TPP/Data Recipient.

2022-11-02 03:47 UTC, isharailanga commented on sandbox-guide.md
> +   - CDR Dynamic Client Registration API: To create Dynamic Client Registration (DCR) Applications
Fixed in fd8b504c8796b29d9d670bb64b77414914ff4082

2022-11-02 03:47 UTC, isharailanga commented on sandbox-guide.md
> +- If you already have a Client ID of a registered application in the portal, skip the steps above.
Fixed in fd8b504c8796b29d9d670bb64b77414914ff4082

2022-11-02 03:47 UTC, isharailanga commented on sandbox-guide.md
> +- From the response, copy the **Client ID** of the application.
Fixed in fd8b504c8796b29d9d670bb64b77414914ff4082

2022-11-02 03:47 UTC, isharailanga commented on sandbox-guide.md
> +- In the **Security** section, enter the access token obtained in the previous step.
Fixed in fd8b504c8796b29d9d670bb64b77414914ff4082

2022-11-02 03:47 UTC, isharailanga commented on sandbox-guide.md
> +- In the **Security** section, enter the access token obtained in the previous step.
Fixed in fd8b504c8796b29d9d670bb64b77414914ff4082

2022-11-02 03:50 UTC, isharailanga commented on sandbox-guide.md
> +## Sign up as an API consumer
Refer to 📧 Mail "Replacing a term in OB documentation and its SEO impact" for more info.

2022-11-02 06:37 UTC, isharailanga commented on sandbox-guide.md
> +- In the **Security** section, enter the access token obtained in the previous step.
Fixed in a2e05cae66472040572fb64657f76a83bbebb341

2022-11-02 08:33 UTC, isharailanga commented on sandbox-guide.md
> +- In the **Security** section, enter the access token obtained in the previous step.
Fixed in 0e0a156214aa7db842741a08f259af3ba0c35cea

2022-11-02 09:46 UTC, ChinthakaJ98 approved these changes

2022-11-02 10:07 UTC, dimuthnc approved these changes

2022-11-02 10:08 UTC, merged